"""add_password_hash_column

Revision ID: 16e5a5a54c2f
Revises: 
Create Date: 2023-09-02 15:18:27.801354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16e5a5a54c2f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('customers', sa.Column('last_name', sa.String(length=100), nullable=False))
    op.drop_column('customers', 'name')
    op.add_column('restaurants', sa.Column('restaurant_name', sa.String(length=100), nullable=False))
    op.add_column('restaurants', sa.Column('restaurant_price', sa.Integer(), nullable=True))
    op.drop_column('restaurants', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('name', sa.VARCHAR(length=100), nullable=False))
    op.drop_column('restaurants', 'restaurant_price')
    op.drop_column('restaurants', 'restaurant_name')
    op.add_column('customers', sa.Column('name', sa.VARCHAR(length=100), nullable=False))
    op.drop_column('customers', 'last_name')
    op.drop_column('customers', 'first_name')
    # ### end Alembic commands ###
